/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tp.dsw.vista;

/**
 *
 * @author Usuario
 */
public class JplCliente extends javax.swing.JPanel {

    /**
     * Creates new form JplCliente
     */
    public JplCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelAgregar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiarAgregar = new javax.swing.JButton();
        txtLongitudAgregar = new javax.swing.JTextField();
        txtLatitudAgregar = new javax.swing.JTextField();
        txtDireccionAgregar = new javax.swing.JTextField();
        txtNombreAgregar = new javax.swing.JTextField();
        jPanelModificar = new javax.swing.JPanel();
        txtIdModificar = new javax.swing.JTextField();
        txtNombreModificar = new javax.swing.JTextField();
        txtDireccionModificar = new javax.swing.JTextField();
        txtLatitudModificar = new javax.swing.JTextField();
        txtLongitudModificar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnLimpiarModificar = new javax.swing.JButton();
        jPanelEliminar = new javax.swing.JPanel();
        btnLimpiarEliminar = new javax.swing.JButton();
        txtIdEliminar = new javax.swing.JTextField();
        txtNombreEliminar = new javax.swing.JTextField();
        txtDireccionEliminar = new javax.swing.JTextField();
        txtLatitudEliminar = new javax.swing.JTextField();
        txtLongitudEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jPanelBuscar = new javax.swing.JPanel();
        btnLimpiarBuscar = new javax.swing.JButton();
        txtIdBuscar = new javax.swing.JTextField();
        txtNombreBuscar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVendedorDatos = new javax.swing.JTable();
        btnPedidos = new javax.swing.JButton();
        btnVerDetalles = new javax.swing.JButton();
        btnCargarDatos = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(960, 420));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "CLIENTES",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanelAgregar.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        btnLimpiarAgregar.setText("Limpiar");
        btnLimpiarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAgregarActionPerformed(evt);
            }
        });
        jPanelAgregar.add(btnLimpiarAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtLongitudAgregar.setForeground(new java.awt.Color(51, 51, 51));
        txtLongitudAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder("Longitud"));
        txtLongitudAgregar.setFocusCycleRoot(true);
        txtLongitudAgregar.setName(""); // NOI18N
        txtLongitudAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudAgregarActionPerformed(evt);
            }
        });
        jPanelAgregar.add(txtLongitudAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, -1));

        txtLatitudAgregar.setForeground(new java.awt.Color(51, 51, 51));
        txtLatitudAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder("Latitud"));
        txtLatitudAgregar.setFocusCycleRoot(true);
        txtLatitudAgregar.setName(""); // NOI18N
        txtLatitudAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudAgregarActionPerformed(evt);
            }
        });
        jPanelAgregar.add(txtLatitudAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        txtDireccionAgregar.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccionAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        txtDireccionAgregar.setFocusCycleRoot(true);
        txtDireccionAgregar.setName(""); // NOI18N
        txtDireccionAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionAgregarActionPerformed(evt);
            }
        });
        jPanelAgregar.add(txtDireccionAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));

        txtNombreAgregar.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txtNombreAgregar.setFocusCycleRoot(true);
        txtNombreAgregar.setName(""); // NOI18N
        txtNombreAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAgregarActionPerformed(evt);
            }
        });
        jPanelAgregar.add(txtNombreAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, -1));

        jTabbedPane.addTab("Agregar", jPanelAgregar);

        jPanelModificar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelModificarPropertyChange(evt);
            }
        });
        jPanelModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdModificar.setForeground(new java.awt.Color(51, 51, 51));
        txtIdModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdModificar.setFocusCycleRoot(true);
        txtIdModificar.setName(""); // NOI18N
        txtIdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(txtIdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, -1));

        txtNombreModificar.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txtNombreModificar.setFocusCycleRoot(true);
        txtNombreModificar.setName(""); // NOI18N
        txtNombreModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(txtNombreModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, -1));

        txtDireccionModificar.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccionModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        txtDireccionModificar.setFocusCycleRoot(true);
        txtDireccionModificar.setName(""); // NOI18N
        txtDireccionModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(txtDireccionModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));

        txtLatitudModificar.setForeground(new java.awt.Color(51, 51, 51));
        txtLatitudModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Latitud"));
        txtLatitudModificar.setFocusCycleRoot(true);
        txtLatitudModificar.setName(""); // NOI18N
        txtLatitudModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(txtLatitudModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        txtLongitudModificar.setForeground(new java.awt.Color(51, 51, 51));
        txtLongitudModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Longitud"));
        txtLongitudModificar.setFocusCycleRoot(true);
        txtLongitudModificar.setName(""); // NOI18N
        txtLongitudModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(txtLongitudModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        btnLimpiarModificar.setText("Limpiar");
        btnLimpiarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarModificarActionPerformed(evt);
            }
        });
        jPanelModificar.add(btnLimpiarModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jTabbedPane.addTab("Modificar", jPanelModificar);

        jPanelEliminar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelEliminarFocusGained(evt);
            }
        });
        jPanelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseClicked(evt);
            }
        });
        jPanelEliminar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelEliminarPropertyChange(evt);
            }
        });
        jPanelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiarEliminar.setText("Limpiar");
        btnLimpiarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(btnLimpiarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtIdEliminar.setForeground(new java.awt.Color(51, 51, 51));
        txtIdEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdEliminar.setFocusCycleRoot(true);
        txtIdEliminar.setName(""); // NOI18N
        txtIdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(txtIdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, -1));

        txtNombreEliminar.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txtNombreEliminar.setFocusCycleRoot(true);
        txtNombreEliminar.setName(""); // NOI18N
        txtNombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(txtNombreEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, -1));

        txtDireccionEliminar.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccionEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        txtDireccionEliminar.setFocusCycleRoot(true);
        txtDireccionEliminar.setName(""); // NOI18N
        txtDireccionEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(txtDireccionEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));

        txtLatitudEliminar.setForeground(new java.awt.Color(51, 51, 51));
        txtLatitudEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Latitud"));
        txtLatitudEliminar.setFocusCycleRoot(true);
        txtLatitudEliminar.setName(""); // NOI18N
        txtLatitudEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(txtLatitudEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        txtLongitudEliminar.setForeground(new java.awt.Color(51, 51, 51));
        txtLongitudEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Longitud"));
        txtLongitudEliminar.setFocusCycleRoot(true);
        txtLongitudEliminar.setName(""); // NOI18N
        txtLongitudEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(txtLongitudEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanelEliminar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jTabbedPane.addTab("Eliminar", jPanelEliminar);

        jPanelBuscar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelBuscarPropertyChange(evt);
            }
        });
        jPanelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiarBuscar.setText("Limpiar");
        btnLimpiarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBuscarActionPerformed(evt);
            }
        });
        jPanelBuscar.add(btnLimpiarBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtIdBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtIdBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdBuscar.setFocusCycleRoot(true);
        txtIdBuscar.setName(""); // NOI18N
        txtIdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBuscarActionPerformed(evt);
            }
        });
        txtIdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdBuscarKeyReleased(evt);
            }
        });
        jPanelBuscar.add(txtIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, -1));

        txtNombreBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txtNombreBuscar.setFocusCycleRoot(true);
        txtNombreBuscar.setName(""); // NOI18N
        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });
        txtNombreBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreBuscarKeyReleased(evt);
            }
        });
        jPanelBuscar.add(txtNombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, -1));

        jTabbedPane.addTab("Buscar", jPanelBuscar);

        jPanel2.add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 390));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        tbVendedorDatos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        {},
                        {},
                        {},
                        {}
                },
                new String[] {

                }));
        tbVendedorDatos.setShowGrid(false);
        tbVendedorDatos.getTableHeader().setResizingAllowed(false);
        tbVendedorDatos.getTableHeader().setReorderingAllowed(false);
        tbVendedorDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVendedorDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVendedorDatos);

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnVerDetalles.setText("Detalles");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(btnPedidos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnVerDetalles))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(9, Short.MAX_VALUE)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnVerDetalles)
                                        .addComponent(btnPedidos))
                                .addGap(0, 13, Short.MAX_VALUE)));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 570, 260));

        btnCargarDatos.setText("CargarDatos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(btnCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarAgregarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnLimpiarAgregarActionPerformed

    private void txtLongitudAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLongitudAgregarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLongitudAgregarActionPerformed

    private void txtLatitudAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLatitudAgregarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLatitudAgregarActionPerformed

    private void txtDireccionAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDireccionAgregarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDireccionAgregarActionPerformed

    private void txtNombreAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreAgregarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreAgregarActionPerformed

    private void txtIdModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIdModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtIdModificarActionPerformed

    private void txtNombreModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreModificarActionPerformed

    private void txtDireccionModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDireccionModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDireccionModificarActionPerformed

    private void txtLatitudModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLatitudModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLatitudModificarActionPerformed

    private void txtLongitudModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLongitudModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLongitudModificarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnLimpiarModificarActionPerformed

    private void jPanelModificarPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jPanelModificarPropertyChange
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanelModificarPropertyChange

    private void btnLimpiarEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnLimpiarEliminarActionPerformed

    private void txtIdEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIdEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtIdEliminarActionPerformed

    private void txtNombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreEliminarActionPerformed

    private void txtDireccionEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDireccionEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDireccionEliminarActionPerformed

    private void txtLatitudEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLatitudEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLatitudEliminarActionPerformed

    private void txtLongitudEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLongitudEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLongitudEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEliminarActionPerformed

    private void jPanelEliminarFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPanelEliminarFocusGained
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanelEliminarFocusGained

    private void jPanelEliminarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanelEliminarMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanelEliminarMouseClicked

    private void jPanelEliminarPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jPanelEliminarPropertyChange
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanelEliminarPropertyChange

    private void btnLimpiarBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarBuscarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnLimpiarBuscarActionPerformed

    private void txtIdBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtIdBuscarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtIdBuscarActionPerformed

    private void txtIdBuscarKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtIdBuscarKeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_txtIdBuscarKeyReleased

    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreBuscarActionPerformed

    private void txtNombreBuscarKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNombreBuscarKeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreBuscarKeyReleased

    private void jPanelBuscarPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jPanelBuscarPropertyChange
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanelBuscarPropertyChange

    private void tbVendedorDatosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbVendedorDatosMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_tbVendedorDatosMouseClicked

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnPedidosActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVerDetallesActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCargarDatosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCargarDatosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiarAgregar;
    private javax.swing.JButton btnLimpiarBuscar;
    private javax.swing.JButton btnLimpiarEliminar;
    private javax.swing.JButton btnLimpiarModificar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAgregar;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable tbVendedorDatos;
    private javax.swing.JTextField txtDireccionAgregar;
    private javax.swing.JTextField txtDireccionEliminar;
    private javax.swing.JTextField txtDireccionModificar;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtIdEliminar;
    private javax.swing.JTextField txtIdModificar;
    private javax.swing.JTextField txtLatitudAgregar;
    private javax.swing.JTextField txtLatitudEliminar;
    private javax.swing.JTextField txtLatitudModificar;
    private javax.swing.JTextField txtLongitudAgregar;
    private javax.swing.JTextField txtLongitudEliminar;
    private javax.swing.JTextField txtLongitudModificar;
    private javax.swing.JTextField txtNombreAgregar;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreEliminar;
    private javax.swing.JTextField txtNombreModificar;
    // End of variables declaration//GEN-END:variables
}
